### ISSUE TITLE
Double Kebabs

### ISSUE THREAD

**Issue by jonnyfiveiq** [ManageIQ/approval-ui#27]
Looking at following screen shot, it shows double kebabs on the row and another on dropped row. Should have only the row not dropped row, and right justify the approve/deny, that should really be buttons not just text. thanks

![Double Kebab](https://user-images.githubusercontent.com/2084157/56911624-3ef67c80-6aa5-11e9-8bdf-852d84f2ed46.png)

**Comment by gmcculloug** [comment]
cc @Hyperkid123

**Comment by Hyperkid123** [comment]
@rvsia i believe you know what to do with this.

**Comment by Hyperkid123** [comment]
@jonnyfiveiq we have been following these: https://redhat.invisionapp.com/share/T2PQRHIS534#/screens/349566504

Double kebab is a bug and will be fixed. Changes to the buttons are also easy. But i would probably need some info from Susan to replace the expandable row with classic simple row.

**Comment by gmcculloug** [comment]
Visually verified this is not longer an issue on the latest deployment to Prod env.
